### ISSUE TITLE
Getting error when installing autograd related to missing blas dependencies, which don't seem to be missing

### ISSUE THREAD

**Issue by andreasrobinson** [HIPS/autograd#144]
When I run:
  pip install autograd

I get an error saying 'no lapack/blas resources found' 

However, I have installed openblas.  And it appears to be installed correctly since theano works on the machine, and theano also depends on openblas (in fact the command below for installing openblas was taken from the theano instructions).  Here is the command I used to install numpy, openblas, etc:
 sudo apt-get -y install python-numpy python-scipy python-dev python-pip python-nose g++ libopenblas-dev git

I'm testing this on an ubuntu (14.04) vagrant box (ubuntu/trusty64), with python-2.7.5

I also tried installing Atlas as the blas instead, but that did not seem to help.  For that I used (again per theano recommendations):
sudo apt-get install libatlas3gf-base libatlas-dev

**Comment by mattjj** [comment]
Does `pip install numpy` work?

Autograd doesn't do anything with lapack or the blas directly; it just lists numpy as a dependency in its setup.py, which means pip will try to install it if pip can't find it. I think this issue probably isn't a problem with autograd, but rather a problem with getting numpy installed and recognized by pip.

By the way, using [Anaconda](https://www.continuum.io/downloads) tends to make installing libraries like numpy a lot easier; it comes packaged with its own blas and all that.

**Comment by andreasrobinson** [comment]
Thanks for the response.  I was able to get autograd up and running with anaconda, so looking forward to giving it a try.

By the way, per your question, running 'pip install numpy' did work fine ('requirement already satisfied'), but 'pip install autograd' still failed with the error about the missing blas.

**Comment by mattjj** [comment]
Can you paste the entire output of `pip install autograd`?

**Comment by andreasrobinson** [comment]
Sure, here's the full output.  Thanks for taking the time to dig into this further!  

vagrant@vagrant-ubuntu-trusty-64:~$ pip install autograd
Downloading/unpacking autograd
  Downloading autograd-1.1.6.tar.gz
  Running setup.py (path:/tmp/pip_build_vagrant/autograd/setup.py) egg_info for package autograd
    /tmp/easy_install-qlNDff/scipy-0.18.0/setup.py:322: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command, proceeding with "
    /usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1427: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    /usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1438: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    /usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1441: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_vagrant/autograd/setup.py", line 20, in <module>
        'Programming Language :: Python :: 3.5'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 415, in <module>

      File "setup.py", line 411, in setup_package

      File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 335, in configuration

      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        url='https://github.com/HIPS/autograd',
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 20, in configuration
        'Programming Language :: Python :: 3.5'],
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    Complete output from command python setup.py egg_info:
    /tmp/easy_install-qlNDff/scipy-0.18.0/setup.py:322: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates

  warnings.warn("Unrecognized setuptools command, proceeding with "

/usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1427: UserWarning:

    Atlas (http://math-atlas.sourceforge.net/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [atlas]) or by setting

    the ATLAS environment variable.

  warnings.warn(AtlasNotFoundError.__doc__)

/usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1438: UserWarning:

    Lapack (http://www.netlib.org/lapack/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [lapack]) or by setting

    the LAPACK environment variable.

  warnings.warn(LapackNotFoundError.__doc__)

/usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1441: UserWarning:

    Lapack (http://www.netlib.org/lapack/) sources not found.

    Directories to search for the sources can be specified in the

    numpy/distutils/site.cfg file (section [lapack_src]) or by setting

    the LAPACK_SRC environment variable.

  warnings.warn(LapackSrcNotFoundError.__doc__)

Running from scipy source directory.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_vagrant/autograd/setup.py", line 20, in <module>

    'Programming Language :: Python :: 3.5'],

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup

    lambda: execfile(

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run

    return func()

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "setup.py", line 415, in <module>



  File "setup.py", line 411, in setup_package



  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup

    config = configuration()

  File "setup.py", line 335, in configuration



  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage

    caller_level = 2)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "scipy/setup.py", line 15, in configuration

    url='https://github.com/HIPS/autograd',

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage

    caller_level = 2)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "scipy/linalg/setup.py", line 20, in configuration

    'Programming Language :: Python :: 3.5'],

numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_vagrant/autograd
Storing debug log for failure in /tmp/tmpvJJBXT
vagrant@vagrant-ubuntu-trusty-64:~$

**Comment by mattjj** [comment]
Thanks! Okay, it looks like the error is in installing scipy (which is also just an autograd dependency), so that `pip install scipy` would probably give the same error when run with the same pip.

I'm going to close the issue because it looks like a scipy problem, and because it sounds like you got things working with anaconda.

**Comment by andreasrobinson** [comment]
Sounds good.  Though actually 'pip install scipy' also works, and outputs 'requirement already satisfied'

**Comment by mattjj** [comment]
I should have added the version strings (since that is probably what's making pip try to install scipy/numpy): `pip install numpy>=1.10 scipy>=0.17` should fail.

In any case, the log shows it's failing in installing scipy and/or numpy, despite my poor guesswork at making a failing pip command.

**Comment by yukoba** [comment]
Ubuntu 14.04 NumPy is 1.8.1 and it is too old.
http://packages.ubuntu.com/trusty/python-numpy

I think you should use Anaconda or Ubuntu 16.04.
