### ISSUE TITLE
support for np.<ufunc>(..., dtype=...)

### ISSUE THREAD

**Issue by anntzer** [HIPS/autograd#166]
Ufuncs support passing a dtype kwarg to pick the output value.  This is particularly useful for casting the output to complex.

For example, the function `lambda x: np.real_if_close(np.cos(np.arccos(x, dtype=complex) / 3))` is real valued for `x>=-1`, despite the complex intermediate value.  Currently, autograd errors on trying to differentiate such a function.  It is possibly to workaround this by removing the `dtype` kwarg and explicitly passing in a complex argument to `grad(func)`, but more direct support would be appreciated.

Alternatively, support for terms of the form `x = x.astype(complex)` would already help (one would just have to call that before calling the ufunc).

**Comment by mattjj** [comment]
We just rolled in a big rewrite of the core yesterday. Can you check if your use case works on 0f026ab?

**Comment by anntzer** [comment]
```
$ python3 -c 'from autograd import grad, numpy as np; grad(lambda x: np.cos(np.arccos(x, dtype=complex) / 3))(.5)'
```
Both as of master and 0f026ab:
```
Traceback (most recent call last):
  File "/home/antony/src/extern/autograd/autograd/core.py", line 31, in forward_pass
    try: end_node = fun(*args, **kwargs)
  File "<string>", line 1, in <lambda>
  File "/home/antony/src/extern/autograd/autograd/core.py", line 139, in __call__
    gradfun = self.gradmaker(argnum, result, args, kwargs)
  File "/home/antony/src/extern/autograd/autograd/core.py", line 100, in gradmaker
    return self.grads[argnum](ans, *args, **kwargs)
TypeError: <lambda>() got an unexpected keyword argument 'dtype'
```
(in 0f026ab, this chains into the exception that I fixed in #165).

**Comment by mattjj** [comment]
Excellent, so this isn't a reversion!

The fix is probably simple: the lambda passed into anp.arccos.defjvp probably just needs a dtype argument added, though I'm afk and typing this on my phone so I can't easily check right now.

**Comment by eric-wieser** [comment]
Worth noting that in numpy 1.13 `__array_ufunc__` was added, which should make it easier to override this kind of thing
