### ISSUE TITLE
error: failed to install autograd

### ISSUE THREAD

**Issue by liujiaxing** [HIPS/autograd#171]
my environment is ubuntu 14.04, with python version 2.7.12 and pip 9.0.1
after running `pip install autograd` it replied the following error:
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-scJP6r/autograd/
When using pip to install other packages there is no error, so does this mean that my environment is not compatible with autograd? thanks.

**Comment by mattjj** [comment]
Can you try running `pip install -v autograd` and show us the specific error that gets printed?

**Comment by liujiaxing** [comment]
Hi, @mattjj, the following is the log of running `pip install -v autograd`, start from error message

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hDtgXn/autograd/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hDtgXn/autograd/

**Comment by mattjj** [comment]
Hmm that doesn't seem to provide any useful information. I don't have any ideas for what's going on, especially since the error isn't happening in autograd code.

You could try installing from a git clone of the source instead of from pip. That is, something like

```
git clone https://github.com/hips/autograd.git
pip install -e autograd
```

**Comment by liujiaxing** [comment]
thanks, this approach works for me.

**Comment by liujiaxing** [comment]
however, test of example Variational inference in Bayesian neural network replied an import error: 

> from black_box_svi import black_box_variational_inference
ImportError: No module named black_box_svi

**Comment by liujiaxing** [comment]
In order to test autograd, I also write a piece of code as follows:

> import numpy as np
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
from mpl_toolkits.mplot3d import Axes3D
from sklearn import mixture
import numpy.matlib as nm
from autograd import grad  
def gmmfunc(x, y):
 g1 = mlab.bivariate_normal(x, y, 1.0, 1.0, -1, -1, -0.8)
 g2 = mlab.bivariate_normal(x, y, 1.5, 0.8, 1, 2, 0.6)
 return 0.6*g1+28.4*g2/(0.6+28.4) 
gmmgrad = grad(gmmfunc)
value = gmmgrad(3,4)
print "grad: ", value

run the above code replied:

> Traceback (most recent call last):
  File "test3.py", line 17, in <module>
    value = gmmgrad(3,4)
  File "/home/eric/autograd/autograd/convenience_wrappers.py", line 25, in gradfun
    vjp, _ = make_vjp(scalar_fun, argnum)(*args, **kwargs)
  File "/home/eric/autograd/autograd/core.py", line 14, in vjp
    start_node, end_node = forward_pass(fun, args, kwargs, argnum)
  File "/home/eric/autograd/autograd/core.py", line 27, in forward_pass
    except Exception as e: add_extra_error_message(e)
  File "/home/eric/autograd/autograd/errors.py", line 57, in add_extra_error_message
    raise_(etype, value, traceback)
  File "/home/eric/autograd/autograd/core.py", line 26, in forward_pass
    try: end_node = fun(*args, **kwargs)
  File "/home/eric/autograd/autograd/convenience_wrappers.py", line 19, in scalar_fun
    return as_scalar(fun(*args, **kwargs))
  File "test3.py", line 10, in gmmfunc
    g1 = mlab.bivariate_normal(x, y, 1.0, 1.0, -1, -1, -0.8)
  File "/usr/lib/pymodules/python2.7/matplotlib/mlab.py", line 1084, in bivariate_normal
    return np.exp( -z/(2*(1-rho**2))) / denom
AttributeError: 'ArrayNode' object has no attribute 'exp'

does this means that autograd still not install correctly?

**Comment by mattjj** [comment]
You need `import autograd.numpy as np` instead of `import numpy as np`. See the [tutorial](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md) and [examples](https://github.com/HIPS/autograd/tree/master/examples). Autograd may not work with `sklearn.mixture` or `mlab.bivariate_normal` because those modules might internally import numpy rather than our wrapped version, so you may need to redefine those functions yourself.

Since you got autograd installed, and we haven't heard of this same pip issue popping up elsewhere, I'm going to close this issue.
