### ISSUE TITLE
Problem with vector assignment

### ISSUE THREAD

**Issue by brunojacobs** [HIPS/autograd#177]
I have encountered a problem when using autograd on specific functions that I am not able to solve. It occurs when a function contains a local variable that is a numpy array in which intermediate results are stored. I can probably best explain this by means of the following minimum example:

```python
from autograd import grad
from autograd import numpy as np

eta = np.random.standard_normal((5, 3))

# autograd works
def f1(param):
    res = np.sum(param * param[0], axis=1)
    return np.sum(res, axis=0)
print('f1:', f1(eta))
ag_f1 = grad(f1, 0)
print(ag_f1(eta))


# autograd does not work
def f2(param):
    res = np.zeros(5)
    for m in range(5):
        res[m] = np.sum(param[m] * param[0])
    return np.sum(res)
print('f2:', f2(eta))
ag_f2 = grad(f2, 0)
print(ag_f2(eta))

```

These two functions are equivalent, and should result in the same output and gradient.

This results in the following output:

```python
bruno$ python scratch.py
f1: 0.640560618546
[[-0.48734979  1.77265289  1.7501133 ]
 [-0.64951507  1.3475087   0.1051734 ]
 [-0.64951507  1.3475087   0.1051734 ]
 [-0.64951507  1.3475087   0.1051734 ]
 [-0.64951507  1.3475087   0.1051734 ]]
f2: 0.640560618546
Traceback (most recent call last):
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/autograd/core.py", line 26, in forward_pass
    try: end_node = fun(*args, **kwargs)
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/autograd/convenience_wrappers.py", line 19, in scalar_fun
    return as_scalar(fun(*args, **kwargs))
  File "scratch.py", line 19, in f2
    res[m] = np.sum(param[m] * param[0])
ValueError: setting an array element with a sequence.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scratch.py", line 23, in <module>
    print(ag_f2(eta))
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/autograd/convenience_wrappers.py", line 25, in gradfun
    vjp, ans = make_vjp(scalar_fun, argnum)(*args, **kwargs)
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/autograd/core.py", line 14, in vjp
    start_node, end_node = forward_pass(fun, args, kwargs, argnum)
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/autograd/core.py", line 27, in forward_pass
    except Exception as e: add_extra_error_message(e)
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/autograd/errors.py", line 57, in add_extra_error_message
    raise_(etype, value, traceback)
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/future/utils/__init__.py", line 414, in raise_
    raise exc.with_traceback(tb)
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/autograd/core.py", line 26, in forward_pass
    try: end_node = fun(*args, **kwargs)
  File "/Users/bruno/anaconda3/lib/python3.5/site-packages/autograd/convenience_wrappers.py", line 19, in scalar_fun
    return as_scalar(fun(*args, **kwargs))
  File "scratch.py", line 19, in f2
    res[m] = np.sum(param[m] * param[0])
ValueError: setting an array element with a sequence.
```

So the functions `f1` and `f2` return the same output, but I am not able to take the gradient of `f2` using autograd. The above is of course a very stylized example, but in some more complex code I am running in essentially the same problem. Is there a way to solve this error? And am I missing something? Based on the restrictions in the autograd tutorial these operations should be OK as far as I can tell.

**Comment by mattjj** [comment]
Autograd doesn't support assignment into arrays, so to use autograd you have to rewrite your code to avoid it. See the tutorial for a bit more info.
