### ISSUE TITLE
I cannot install autograd in python2.7

### ISSUE THREAD

**Issue by JeongMinCha** [HIPS/autograd#180]
My python version is ```2.7.10``` and pip2.7 is ```9.0.1```
I want to use [pyhawkes](https://github.com/slinderman/pyhawkes) but I cannot use it because I cannot use autograd. (pyhawkes module seems using autograd.numpy in python2 environment) 
I typed ```pip2.7 install autograd``` to install this module but it shows the below error message:
```
... 
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5f/y65b94ss76z10jc33dk5km6m0000gn/T/pip-build-hyWiQo/autograd/setup.py", line 20, in <module>
        'Programming Language :: Python :: 3.5'],
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 843, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1088, in best_match
        return self.obtain(req, installer)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1100, in obtain
        return installer(requirement)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 638, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 668, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 851, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1079, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1067, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: library dfftpack has Fortran sources but no Fortran compiler found
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5f/y65b94ss76z10jc33dk5km6m0000gn/T/pip-build-hyWiQo/autograd/
```
There's other error messages above this error message, but I couldn't paste them because they are too long to write it here.

How could I solve this problem?

**Comment by mattjj** [comment]
This error isn't coming from autograd; we don't have any Fortran code. It must be [one of the packages autograd depends on](https://github.com/HIPS/autograd/blob/fd3521dcd2989155fad924a9dc941d30b58daa43/setup.py#L10), namely numpy or scipy. It sounds like it could be [this scipy problem](https://github.com/scipy/scipy/issues/4102),  or a similar one.

If that's right, then you need either to get scipy installed or to set up your environment so that pip can install it for you (e.g. by installing a Fortran compiler). Personally I tend to install numpy and scipy without pip by using the conda package manager from the [Anaconda Python distribution](https://www.continuum.io/downloads).
