### ISSUE TITLE
cannot define gradient of instance method

### ISSUE THREAD

**Issue by agocsfruzsina** [HIPS/autograd#195]
Hi,

I'm trying to define my own gradient of an instance method,

```python
class OscillationSolution():
    def __init__(self, ti, tf, xi, ui, rtol, hmin, hmax ):
        self.f3plus.defvjp(self.d_f3plus)
    
    @primitive
    def f3plus(self, g, ans, vs, gvs, t):
        return 1.0/(self.w(t)**0.5)*np.exp(sum(self.S))

    def d_f3plus(self, t):
        return -1.0/(2*self.w(t))*grad(self.w)(t) + sum([self.dS0(t), self.dS1(t), self.dS2(t), self.dS3(t)])*ans*g
```

but this gives an `AttributeError`:
```
Traceback (most recent call last):
  File "./RKF_reduced.py", line 230, in <module>
    Solution = OscillationSolution(ti, tf, yi, ui, tol, hmin, hmax)
  File "./RKF_reduced.py", line 47, in __init__
    self.f3plus.defvjp(self.d_f3plus)
  File "/home/fa325/.local/lib/python2.7/site-packages/autograd/core.py", line 87, in defvjp
    vjpmaker.__name__ = "VJP_{}_of_{}".format(argnum, self.__name__)
AttributeError: 'instancemethod' object has no attribute '__name__'
```

Do I need to define `f3plus` outside of its class for this to work?
Thanks.
P.S. Thanks for the awesome library :)

**Comment by mattjj** [comment]
Bound methods make argument numbers confusing, but I think autograd should still work here.

Here's a template that seems to work and that you might be able to follow:

```python
import autograd.numpy as np
from autograd.core import primitive
from autograd import grad

class A(object):
    @primitive
    def f(self, x):
        return x**2

    f.defvjp(lambda g, ans, vs, gvs, self, x: 2.*x, argnum=1)

a = A()
print a.f(3.)
print grad(a.f)(3.)
print grad(grad(a.f))(3.)
```

(I'm using Python 2.7, and this code seems to run with both [old- and new-style classes](https://docs.python.org/2/reference/datamodel.html#new-style-and-classic-classes), i.e. both inheriting and not inheriting from `object`.)

If pattern-matching this example doesn't work, or if something else is amiss, please reopen!
