### ISSUE TITLE
Examples using mvn.logpdf fail

### ISSUE THREAD

**Issue by sanket-kamthe** [HIPS/autograd#201]
This is an interesting bug:

This works:

```python
import autograd.numpy as np
from autograd.scipy.stats import multivariate_normal as mvn
from autograd import grad, jacobian
from autograd.util import check_grads, to_scalar

mean = np.array([0, 0])
cov = np.array([[1, 0], [0, 100]])
x = np.random.multivariate_normal(mean, cov, 10)
loglik = lambda x:  mvn.logpdf(x, mean=mean, cov=cov); 
grad_loglik = lambda u: to_scalar(jacobian(loglik)(u))
check_grads(grad_loglik, x)
```

Failing example:
autograd/examples/gaussian_process.py

```shell
(tensorflow) sk15@scramble:~/Documents/Github/autograd$ python ./examples/gaussian_process.py 
Optimizing covariance parameters...
Traceback (most recent call last):
  File "/home/sk15/Documents/Github/autograd/autograd/errors.py", line 48, in wrapped
    try: return fun(*args, **kwargs)
  File "/home/sk15/Documents/Github/autograd/autograd/convenience_wrappers.py", line 28, in gradfun
    return vjp(cast_to_same_dtype(1.0, ans))
  File "/home/sk15/Documents/Github/autograd/autograd/core.py", line 18, in <lambda>
    return lambda g : backward_pass(g, end_node, start_node), end_node
  File "/home/sk15/Documents/Github/autograd/autograd/core.py", line 40, in backward_pass
    parent.vspace, node.vspace, args, kwargs)
  File "/home/sk15/Documents/Github/autograd/autograd/core.py", line 77, in vjp
    return self.vjps[argnum](outgrad, ans, vs, gvs, *args, **kwargs)
TypeError: <lambda>() takes 7 positional arguments but 8 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./examples/gaussian_process.py", line 109, in <module>
    method='CG', callback=callback)
  File "/home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 442, in minimize
    return _minimize_cg(fun, x0, args, jac, callback, **options)
  File "/home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 1228, in _minimize_cg
    gfk = myfprime(x0)
  File "/home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 71, in derivative
    self(x, *args)
  File "/home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/home/sk15/Documents/Github/autograd/autograd/convenience_wrappers.py", line 125, in <lambda>
    return lambda *args, **kwargs: flip(*gradval_and_val(*args, **kwargs))
  File "/home/sk15/Documents/Github/autograd/autograd/convenience_wrappers.py", line 135, in grad_and_aux_fun
    gradval = grad(return_val_save_aux, argnum)(*args, **kwargs)
  File "/home/sk15/Documents/Github/autograd/autograd/errors.py", line 49, in wrapped
    except Exception as e: add_extra_error_message(e)
  File "/home/sk15/Documents/Github/autograd/autograd/errors.py", line 71, in add_extra_error_message
    raise_(etype, value, traceback)
  File "/home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages/future/utils/__init__.py", line 413, in raise_
    raise exc.with_traceback(tb)
  File "/home/sk15/Documents/Github/autograd/autograd/errors.py", line 48, in wrapped
    try: return fun(*args, **kwargs)
  File "/home/sk15/Documents/Github/autograd/autograd/convenience_wrappers.py", line 28, in gradfun
    return vjp(cast_to_same_dtype(1.0, ans))
  File "/home/sk15/Documents/Github/autograd/autograd/core.py", line 18, in <lambda>
    return lambda g : backward_pass(g, end_node, start_node), end_node
  File "/home/sk15/Documents/Github/autograd/autograd/core.py", line 40, in backward_pass
    parent.vspace, node.vspace, args, kwargs)
  File "/home/sk15/Documents/Github/autograd/autograd/core.py", line 77, in vjp
    return self.vjps[argnum](outgrad, ans, vs, gvs, *args, **kwargs)
TypeError: <lambda>() takes 7 positional arguments but 8 were given
```

For that matter all examples using mvn.logpdf fail.
Same error for the following examples
2) autograd/examples/gplvm.py
3) autograd/examples/bayesian_optimisation.py

Haven't tested others but I suspect the result is same. 
Fails with same error for my local GP regression code. Hand written loglikelihood using autograd.numpy works!

Other info:

I am master branch of autograd (forced upgrade before submitting issue, failed before and after update)
I am using anaconda build with numpy-1.12.0 and scipy-0.19.0

bash on install for further details
```shell
(tensorflow) sk15@srcamble:~/Documents/Github/autograd$ pip install --upgrade .
Processing /home/sk15/Documents/Github/autograd
Requirement already up-to-date: numpy>=1.10 in /home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages (from autograd==1.1.9)
Requirement already up-to-date: scipy>=0.17 in /home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages (from autograd==1.1.9)
Requirement already up-to-date: future>=0.15.2 in /home/sk15/anaconda3/envs/tensorflow/lib/python3.5/site-packages (from autograd==1.1.9)
Installing collected packages: autograd
  Found existing installation: autograd 1.1.9
    Uninstalling autograd-1.1.9:
      Successfully uninstalled autograd-1.1.9
  Running setup.py install for autograd ... done
Successfully installed autograd-1.1.9

```

**Comment by j-towns** [comment]
It looks like the optional `allow_singular` argument breaks the gradient. A minimal example is

```python
from autograd.scipy.stats import multivariate_normal as mvn
from autograd import grad

mean = np.array([0, 0])
cov = np.array([[1, 0], [0, 100]])

loglik = lambda x:  mvn.logpdf(x, mean=mean, cov=cov, allow_singular=True)

grad(loglik)(np.random.randn(2))
```
I've submitted a pr to fix this.

**Comment by sanket-kamthe** [comment]
Thanks.
Fixes my code as well !
