### ISSUE TITLE
Errors while using grad

### ISSUE THREAD

**Issue by nishnik** [HIPS/autograd#246]
Why doesn't this work:
```
import autograd.numpy as np
from autograd import grad
from math import *

def loss_n(x):
    return exp(np.dot(x,x))

grad_ = grad(loss_n)

tmp = np.asarray([2.0, 2.0])

loss_n(tmp)
```
I get the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/autograd/errors.py", line 48, in wrapped
    try: return fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/convenience_wrappers.py", line 27, in gradfun
    vjp, ans = make_vjp(scalar_fun, argnum)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/core.py", line 14, in vjp
    start_node, end_node = forward_pass(fun, args, kwargs, argnum)
  File "/usr/local/lib/python3.4/dist-packages/autograd/core.py", line 26, in forward_pass
    end_node = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/convenience_wrappers.py", line 20, in scalar_fun
    return as_scalar(fun(*args, **kwargs))
  File "<stdin>", line 2, in loss_n
TypeError: a float is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/autograd/errors.py", line 49, in wrapped
    except Exception as e: add_extra_error_message(e)
  File "/usr/local/lib/python3.4/dist-packages/autograd/errors.py", line 71, in add_extra_error_message
    raise_(etype, value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/future/utils/__init__.py", line 413, in raise_
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/autograd/errors.py", line 48, in wrapped
    try: return fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/convenience_wrappers.py", line 27, in gradfun
    vjp, ans = make_vjp(scalar_fun, argnum)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/core.py", line 14, in vjp
    start_node, end_node = forward_pass(fun, args, kwargs, argnum)
  File "/usr/local/lib/python3.4/dist-packages/autograd/core.py", line 26, in forward_pass
    end_node = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/convenience_wrappers.py", line 20, in scalar_fun
    return as_scalar(fun(*args, **kwargs))
  File "<stdin>", line 2, in loss_n
TypeError: a float is required
```

And if I do:

```
import autograd.numpy as np
from autograd import grad
from math import *

def loss_n(x):
    return exp(float(np.dot(x,x)))

grad_ = grad(loss_n)

tmp = np.asarray([2.0, 2.0])

loss_n(tmp)
grad_(tmp)
```
Then I get:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/autograd/errors.py", line 48, in wrapped
    try: return fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/convenience_wrappers.py", line 27, in gradfun
    vjp, ans = make_vjp(scalar_fun, argnum)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/core.py", line 14, in vjp
    start_node, end_node = forward_pass(fun, args, kwargs, argnum)
  File "/usr/local/lib/python3.4/dist-packages/autograd/core.py", line 26, in forward_pass
    end_node = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/convenience_wrappers.py", line 20, in scalar_fun
    return as_scalar(fun(*args, **kwargs))
  File "<stdin>", line 2, in loss_n
TypeError: float() argument must be a string or a number, not 'ArrayNode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/autograd/errors.py", line 49, in wrapped
    except Exception as e: add_extra_error_message(e)
  File "/usr/local/lib/python3.4/dist-packages/autograd/errors.py", line 71, in add_extra_error_message
    raise_(etype, value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/future/utils/__init__.py", line 413, in raise_
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/autograd/errors.py", line 48, in wrapped
    try: return fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/convenience_wrappers.py", line 27, in gradfun
    vjp, ans = make_vjp(scalar_fun, argnum)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/core.py", line 14, in vjp
    start_node, end_node = forward_pass(fun, args, kwargs, argnum)
  File "/usr/local/lib/python3.4/dist-packages/autograd/core.py", line 26, in forward_pass
    end_node = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autograd/convenience_wrappers.py", line 20, in scalar_fun
    return as_scalar(fun(*args, **kwargs))
  File "<stdin>", line 2, in loss_n
TypeError: float() argument must be a string or a number, not 'ArrayNode'
```

**Comment by dhirschfeld** [comment]
Try using `np.exp`.
