### ISSUE TITLE
Broadcast not working in tanh.py example

### ISSUE THREAD

**Issue by kmundnic** [HIPS/autograd#259]
I'm running Python 2.7.13, autograd 1.1.10. The example tanh.py doesn't work for me:

```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    x, grad(tanh)(x),                                 # first derivative
  File "/Users/karel/anaconda/lib/python2.7/site-packages/autograd/errors.py", line 49, in wrapped
    except Exception as e: add_extra_error_message(e)
  File "/Users/karel/anaconda/lib/python2.7/site-packages/autograd/errors.py", line 71, in add_extra_error_message
    raise_(etype, value, traceback)
  File "/Users/karel/anaconda/lib/python2.7/site-packages/autograd/errors.py", line 48, in wrapped
    try: return fun(*args, **kwargs)
  File "/Users/karel/anaconda/lib/python2.7/site-packages/autograd/convenience_wrappers.py", line 27, in gradfun
    vjp, ans = make_vjp(scalar_fun, argnum)(*args, **kwargs)
  File "/Users/karel/anaconda/lib/python2.7/site-packages/autograd/core.py", line 14, in vjp
    start_node, end_node = forward_pass(fun, args, kwargs, argnum)
  File "/Users/karel/anaconda/lib/python2.7/site-packages/autograd/core.py", line 26, in forward_pass
    end_node = fun(*args, **kwargs)
  File "/Users/karel/anaconda/lib/python2.7/site-packages/autograd/convenience_wrappers.py", line 20, in scalar_fun
    return as_scalar(fun(*args, **kwargs))
  File "/Users/karel/anaconda/lib/python2.7/site-packages/autograd/convenience_wrappers.py", line 230, in as_scalar
    "Try jacobian or elementwise_grad.".format(getval(x)))
TypeError: Output [-0.9981779  -0.99804522 -0.9979029  -0.99775022 -0.99758644 -0.99741076
 -0.9972223  -0.99702015 -0.99680331 -0.99657071 -0.99632123 -0.99605363
 -0.9957666  -0.99545875 -0.99512857 -0.99477444 -0.99439464 -0.99398731
 -0.99355049 -0.99308204 -0.99257969 -0.99204101 -0.99146339 -0.99084405
 -0.99017999 -0.98946802 -0.98870472 -0.98788645 -0.98700928 -0.98606904
 -0.98506126 -0.98398116 -0.98282365 -0.98158327 -0.98025421 -0.97883026
 -0.9773048  -0.97567077 -0.97392065 -0.97204641 -0.97003952 -0.96789089
 -0.96559087 -0.96312917 -0.96049491 -0.95767649 -0.95466165 -0.95143738
 -0.94798991 -0.94430469 -0.94036635 -0.93615866 -0.93166454 -0.926866
 -0.92174416 -0.9162792  -0.91045039 -0.90423604 -0.89761355 -0.89055941
 -0.88304922 -0.8750577  -0.86655881 -0.85752573 -0.84793098 -0.83774653
 -0.82694388 -0.81549421 -0.80336854 -0.79053792 -0.77697361 -0.76264735
 -0.74753158 -0.73159974 -0.7148266  -0.69718856 -0.67866403 -0.65923379
 -0.63888141 -0.61759363 -0.59536077 -0.57217718 -0.5480416  -0.52295756
 -0.49693375 -0.46998435 -0.44212929 -0.41339449 -0.38381202 -0.35342017
 -0.32226348 -0.29039261 -0.25786418 -0.22474049 -0.19108913 -0.15698251
 -0.12249729 -0.08771371 -0.05271491 -0.01758613  0.01758613  0.05271491
  0.08771371  0.12249729  0.15698251  0.19108913  0.22474049  0.25786418
  0.29039261  0.32226348  0.35342017  0.38381202  0.41339449  0.44212929
  0.46998435  0.49693375  0.52295756  0.5480416   0.57217718  0.59536077
  0.61759363  0.63888141  0.65923379  0.67866403  0.69718856  0.7148266
  0.73159974  0.74753158  0.76264735  0.77697361  0.79053792  0.80336854
  0.81549421  0.82694388  0.83774653  0.84793098  0.85752573  0.86655881
  0.8750577   0.88304922  0.89055941  0.89761355  0.90423604  0.91045039
  0.9162792   0.92174416  0.926866    0.93166454  0.93615866  0.94036635
  0.94430469  0.94798991  0.95143738  0.95466165  0.95767649  0.96049491
  0.96312917  0.96559087  0.96789089  0.97003952  0.97204641  0.97392065
  0.97567077  0.9773048   0.97883026  0.98025421  0.98158327  0.98282365
  0.98398116  0.98506126  0.98606904  0.98700928  0.98788645  0.98870472
  0.98946802  0.99017999  0.99084405  0.99146339  0.99204101  0.99257969
  0.99308204  0.99355049  0.99398731  0.99439464  0.99477444  0.99512857
  0.99545875  0.9957666   0.99605363  0.99632123  0.99657071  0.99680331
  0.99702015  0.9972223   0.99741076  0.99758644  0.99775022  0.9979029
  0.99804522  0.9981779 ] can't be cast to float. Function grad requires a scalar-valued function. Try jacobian or elementwise_grad.
```

Seems like broadcasting is not working. If I use `elementwise_grad` in tanh.py instead of `grad`, I am able to replicate the example of the README. Seems to me like broadcasting is not working. Is this intended behavior?

Thanks

**Comment by mattjj** [comment]
I suspect the issue is that you're using the pypi version of autograd rather than the git master version. We hadn't yet updated the pypi version of autograd to have the automatic vectorization  behavior in `grad`.

I just updated the pypi version. Can you try updating and running the example again?

**Comment by kmundnic** [comment]
Thanks Matt. I indeed installed using pip. I have upgraded it to v1.1.11 from v1.1.10, and now the example works.
