### ISSUE TITLE
Assertion failure in Anaconda under Windows

### ISSUE THREAD

**Issue by ltzhang** [HIPS/autograd#33]
neural_net.py and convnet.py have assertion errors in Anaconda Python under Windows 7 64bit (tested on latest Anaconda Python 2.2.0). 

Traceback (most recent call last):
  File "neural_net.py", line 117, in <module>
    quick_grad_check(loss_fun, W, (train_images, train_labels))
  File "C:\Anaconda\lib\site-packages\autograd\util.py", line 98, in quick_grad_check
    analytic_grad = np.sum(grad(fun)(arg0, *extra_args, **kwargs) * random_dir)
  File "C:\Anaconda\lib\site-packages\autograd\core.py", line 15, in gradfun
    return backward_pass(*forward_pass(fun,args,kwargs,argnum))
  File "C:\Anaconda\lib\site-packages\autograd\core.py", line 56, in backward_pass
    og = cast_to_node_type(gradfun(cur_outgrad), parent.node_type, parent.node_value)
  File "C:\Anaconda\lib\site-packages\autograd\numpy\numpy_grads.py", line 346, in new_fun
    assert anp.shape(result) == shape
AssertionError

**Comment by mattjj** [comment]
I think #34 almost certainly fixed this issue.
