### ISSUE TITLE
grad of a function that uses logsumexp fails in some cases

### ISSUE THREAD

**Issue by avital** [HIPS/autograd#336]
The following code fails (stack trace below).
```py
import autograd.numpy as np
from autograd.scipy.misc import logsumexp
from autograd import grad

def f(x):
  return logsumexp(a=np.array([x]))

df = grad(f)
df(0.0)
```

Here's a curious find: Changing `logsumexp(a=np.array([x]))` to `logsumexp(np.array([x]))` (removing the `a=`) fixes the problem. Maybe this can help uncover the source of the problem.

```
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    df(0.0)
  File "/home/avitalo/.local/lib/python2.7/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/home/avitalo/.local/lib/python2.7/site-packages/autograd/differential_operators.py", line 24, in grad
    vjp, ans = _make_vjp(fun, x)
  File "/home/avitalo/.local/lib/python2.7/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/home/avitalo/.local/lib/python2.7/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/home/avitalo/.local/lib/python2.7/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "bug.py", line 6, in f
    return logsumexp(a=np.array([x]))
  File "/home/avitalo/.local/lib/python2.7/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/scipy/misc/common.py", line 157, in logsumexp
    a_max[~isfinite(a_max)] = 0
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any su
pported types according to the casting rule ''safe''
```

P.S. autograd is great.

**Comment by mattjj** [comment]
Glad you like Autograd, Avital!

Actually, in general you can't differentiate through keyword arguments passed to primitives, as [primitives don't inspect `kwargs` for boxes and instead only look through positional arguments](https://github.com/HIPS/autograd/blob/e99d1276653a54114aa8835bef8f831c82c8d3e3/autograd/tracer.py#L37). One reason for that is we like to define primitive functions' VJPs with respect to positional arguments; alternatives like defining them relative to argument names would make the implementation more complex in several places, and doesn't seem to add any significant benefits. (There may be other reasons I'm forgetting...) On a side note, thinking in terms of positional arguments tends to make math notation better too.

Is there a particular use case you have in mind?

We should probably document somewhere that one shouldn't pass keyword arguments (through which one is differentiating) to primitives. It's surprising that it doesn't come up more often!

**Comment by avital** [comment]
Oh, wow! Knowing that would have saved me a lot of time :)

I see the point about controlling implementation complexity. I've maintained open source projects and know the pain of slow uncontrolled complexity creep.

I was calling `logsumpexp`, passing in both the `a` and `b` kwargs. I just liked being explicit about the arguments, but I don't have to.

Even better than documenting would be throwing an explicit, helpful error. I have no sense for how hard or easy this would be.

**Comment by mattjj** [comment]
Let's leave this issue open until we improve the docs (and possibly error messages) on passing kwargs to primitives.

We can also try to improve kwarg support by binding keyword arguments to positional arguments where possible; logic like that already exists in [`multigrad_dict`](https://github.com/HIPS/autograd/blob/e99d1276653a54114aa8835bef8f831c82c8d3e3/autograd/differential_operators.py#L145). Since we have a benchmark suite now, we could try to use some of that machinery in `primitive` and see how much it slows things down.

**Comment by dustinvtran** [comment]
One use case: this doesn't come up yet in autograd because there isn't much `scipy.stats` support, but it's often best practice to specify distributions with kwargs. It's easy to assume the wrong ordering for the positional args and get tripped up in mysterious bugs.

In addition, as I'm building on autograd for Edward, we wrap TF distributions: this supports different parameterizations in the same distribution (e.g., `logits` or `probs`) so it's sensible to use `kwargs`.
