### ISSUE TITLE
list indexing regression?

### ISSUE THREAD

**Issue by mattjj** [HIPS/autograd#341]
@j-towns noticed this in #329 

```
======================================================================
FAIL: _test_complexity.test_list_indexing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jamietownsend/miniconda3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/jamietownsend/dev/autograd/tests/_test_complexity.py", line 35, in test_list_indexing
    assert_linear_time(lambda N: grad(fun)([0.0 for i in range(50*N)]))
  File "/Users/jamietownsend/dev/autograd/tests/_test_complexity.py", line 16, in assert_linear_time
    assert t10 < 20 * t, "Too slow: f(1) takes {}, f(10) takes {}".format(t, t10)
AssertionError: Too slow: f(1) takes 0.02711200714111328, f(10) takes 0.6717362403869629

----------------------------------------------------------------------
```

**Comment by j-towns** [comment]
This appears to be caused by calls to `vspace` [here](https://github.com/HIPS/autograd/blob/master/autograd/builtins.py#L19) and [here](https://github.com/HIPS/autograd/blob/master/autograd/builtins.py#L85). For numpy arrays, time taken by `vspace` doesn't depend on the size of the array. However it would appear that for lists it's roughly linear in the length of the list. The number of times vspace is called is linear too hence quadratic time.

I think it's reasonable for the time taken by `vspace` to be linear for containers, so I guess we should solve this by somehow calling `vspace` only once. For the jvp of make_sequence we could use defjvp_argnums, but for the vjp of take that won't work because take itself is called multiple times in the indexing test. Maybe we could wrap `vspace` in [lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache)? Seems a bit inelegent though...
