### ISSUE TITLE
np.copy

### ISSUE THREAD

**Issue by solitaryangler** [HIPS/autograd#357]
Hi there,
I'm new to autograd. I'm getting a funny error with `np.copy`. To illustrate my error I modified an existing example which also produces the same error:
```
from __future__ import division
import autograd.numpy as np
from autograd import grad

def fun(W, inds):
   W = np.concatenate((W, inds), axis=1)
   W = np.copy(W) ## <-- Error line
   inds = W[:,-1]
   W = W[:,:-1]
   return W[np.int64(inds)].sum()

W = np.random.randn(5, 10)
inds = np.ones(5)[:,None]
g = grad(fun)
print (g(W, inds))
```

I am using python 3.5. The error:

> Traceback (most recent call last):
  File "cost_dotsq.py", line 15, in <module>
    print (g(W, inds))
  File ".../anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File ".../anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/differential_operators.py", line 24, in grad
    vjp, ans = _make_vjp(fun, x)
  File ".../anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File ".../anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File ".../anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "cost_dotsq.py", line 7, in fun
    W = np.copy(W)
  File ".../anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/tracer.py", line 45, in f_wrapped
    node = node_constructor(ans, f_wrapped, argvals, kwargs, argnums, parents)
  File ".../anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/core.py", line 30, in __init__
    self.vjp = primitive_vjps[fun](parent_argnums, value, args, kwargs)
KeyError: <function primitive.<locals>.f_wrapped at 0x7f3e0fb9a9d8>

Thanks for your help.

**Comment by jkitchin** [comment]
I think this means autograd does not have a derivative defined for the copy function. I usually avoid using copy. e.g.:

```
   W = np.concatenate((W, inds), axis=1)
   W0 = np.concatenate((W, inds), axis=1)
```
curiously, this also seems to work:

  ` W = np.array(W, copy=True)`

**Comment by solitaryangler** [comment]
Hi @jkitchin 
thanks for your help. I was able to resole it with your remark:

```W = np.array(W, copy=True)```

This was sufficient to get it to work.
Am closing as resolved.
Thanks and regards.
