### ISSUE TITLE
Hessian with parameters

### ISSUE THREAD

**Issue by solitaryangler** [HIPS/autograd#358]
Hello,

thank you for this fantastic product. The more I am using it, the more I'm enjoying it. But I'm new and not aware of all the intricacies. So I am bumped again. I have two questions:
a) is there an API documentation somewhere? I am unable to find it.
b) I am trying scipy.optimize with hessian and the following is a mock-example that demonstrates my error. Essentially I have a cost-function that takes in multiple parameters:

```
import autograd.numpy as np
from autograd import grad
from autograd import hessian_vector_product
from scipy.optimize import minimize

def myfun(x, ttype, const):
    if ttype=='square':
        f = np.square
    if ttype=='sqrt':
        f = np.sqrt
    return f(np.linalg.norm(x)*const)

if __name__ == '__main__':
    ttype = 'square'
    const = 100.

    costfun = myfun
    costgrd = grad(myfun, argnum=0)
    costhes = hessian_vector_product(myfun, argnum=0)

    x0 = np.random.rand(1, 5)
    res = minimize(costfun, x0, args=(ttype, const), 
                                    jac=costgrd, hessp=costhes,
                                    method='Newton-CG')

    print ('Optimisation res:\n', res)
```

I am getting the following error:

> Traceback (most recent call last):
>   File "mytest.py", line 31, in <module>
>     method='Newton-CG')
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 484, in minimize
>     **options)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 1571, in _minimize_newtoncg
>     Ap = fhess_p(xk, psupi, *args)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/wrap_util.py", line 20, in nary_f
>     return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/differential_operators.py", line 24, in grad
>     vjp, ans = _make_vjp(fun, x)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/core.py", line 10, in make_vjp
>     end_value, end_node =  trace(start_node, fun, x)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/tracer.py", line 10, in trace
>     end_box = fun(start_box)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/wrap_util.py", line 15, in unary_f
>     return fun(*subargs, **kwargs)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/differential_operators.py", line 88, in vector_dot_grad
>     return np.tensordot(fun_grad(*args, **kwargs), vector, np.ndim(vector))
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/wrap_util.py", line 20, in nary_f
>     return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/differential_operators.py", line 24, in grad
>     vjp, ans = _make_vjp(fun, x)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/core.py", line 10, in make_vjp
>     end_value, end_node =  trace(start_node, fun, x)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/tracer.py", line 10, in trace
>     end_box = fun(start_box)
>   File "Softwares/anaconda2/envs/geomni35/lib/python3.5/site-packages/autograd/wrap_util.py", line 15, in unary_f
>     return fun(*subargs, **kwargs)
>   File "mytest.py", line 13, in myfun
>     return f(np.linalg.norm(x)*const)
> UnboundLocalError: local variable 'f' referenced before assignment
> 

I am using Python 3.5.
If I debug, I am able to see that the error occurs when `myfun` is called with wrong parameters.
Normally, I see that `x` is a np.array (or ArrayBox), `ttype` is a string and `const` my float constant. But at crash time, `x` is an ArrayBox (`x._value` doesn't show values but only that `_value` itself is also an ArrayBox), while `ttype` now contains the x-values and therefore none of the if-conditions are satisfied and `const` now contains the string `'square'`.
I believe this is happening when the hessian call occurs.

What am I doing wrong? 

Many thanks

**Comment by jermwatt** [comment]
A few things.  

First off - when you define a function and then pass it too `grad`, any explicit input is treated as a variable to differentative (so in your case the inputs `ttype` and `const`).  Define those elswhere than the definition of `myfun` instead of having them be explicit inputs.

For example, below is a simplified version of your `myfun` without these inputs, and where I have used `ttype = square`.  

```
def myfun(x):
    return np.linalg.norm(x)*const**2
```

The second thing: before trying an outside optimizer try one of the standard ones in the `autograd` library itself located at https://github.com/HIPS/autograd/blob/master/autograd/misc/optimizers.py  This will help make sure there's no problem with your code prior to trying i

For example, you can run a simple gradient descent procedure like below - which works fine on my machine.  

```
# define derivatives and constant
costgrd = grad(myfun)
costhes = hessian_vector_product(myfun)
const = 100.

# run simple gradient descent loop
x = np.random.rand(1, 5)
alpha = 0.1
for i in range(100):
    x = x - alpha*df(x)
```

Having done this I can have some confience that my code thus far works.   If you want to use Newton's method that works natively with `autograd` you can [see an example here](https://jermwatt.github.io/mlrefined/blog_posts/7_Second_order_methods/7_3_Newtons_method.html).

I then tried the minimizer built into scipy you are aiming to use and got the following result.


```
x0 = np.random.rand(1, 5)
res = minimize(myfun, x0,jac=costgrd, hessp=costhes,method='Newton-CG')
print (res)

   fun: 13134.655238629284
     jac: array([ 6351.22086682,  2659.17594877,  1789.08089158,  2489.15536201,
        6572.21971038])
 message: 'Warning: Desired error not necessarily achieved due to precision loss.'
    nfev: 24
    nhev: 1
     nit: 0
    njev: 12
  status: 2
 success: False
       x: array([ 0.83421096,  0.34927359,  0.23498961,  0.32694198,  0.8632384 ])
```
