### ISSUE TITLE
np.diagonal fails

### ISSUE THREAD

**Issue by martinwu42** [HIPS/autograd#372]
The following code fails

```python
import autograd.numpy as np
from autograd import grad


def f(x):
    d = np.diagonal(x)
    s = np.sum(d)
    return s


df = grad(f)
x = np.array([[1, 2], [3, 4]], dtype=float)
print(df(x))
```

The traceback is

```
Traceback (most recent call last):
  File "test_diagonal.py", line 13, in <module>
    print(df(x))
  File "C:\Python36\lib\site-packages\autograd\wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "C:\Python36\lib\site-packages\autograd\differential_operators.py", line 28, in grad
    return vjp(vspace(ans).ones())
  File "C:\Python36\lib\site-packages\autograd\core.py", line 14, in vjp
    def vjp(g): return backward_pass(g, end_node)
  File "C:\Python36\lib\site-packages\autograd\core.py", line 21, in backward_pass
    ingrads = node.vjp(outgrad[0])
  File "C:\Python36\lib\site-packages\autograd\core.py", line 61, in <lambda>
    return lambda g: (vjp(g),)
  File "C:\Python36\lib\site-packages\autograd\numpy\numpy_vjps.py", line 533, in <lambda>
    lambda g: anp.make_diagonal(g, offset, axis1, axis2))
  File "C:\Python36\lib\site-packages\autograd\tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "C:\Python36\lib\site-packages\autograd\numpy\numpy_wrapper.py", line 126, in make_diagonal
    raise NotImplementedError("Currently make_diagonal only supports offset=0, axis1=-1, axis2=-2")
NotImplementedError: Currently make_diagonal only supports offset=0, axis1=-1, axis2=-2
```

However, the arguments of make_diagonal are `offset=0, axis1=0, axis2=1`, and they are identical to `offset=0, axis1=-1, axis2=-2` for a 2D array. If I comment the `raise` lines in `numpy_wrapper.py`, the code works as intended.

**Comment by jermwatt** [comment]
How about using `np.diag` instead of `np.diagonal` in your function `f`?  They both do the same thing there, and it looks like `autograd` can differentiate `np.diag` just fine.

```
import autograd.numpy as np
from autograd import grad

def f(x):
    d = np.diag(x)
    s = np.sum(d)
    return s

df = grad(f)
x = np.array([[1, 2], [3, 4]], dtype=float)
print(df(x))

[[ 1.  0.]
 [ 0.  1.]]
```
