### ISSUE TITLE
getting 'ValueError: setting an array element with a sequence' when computing the jacobian

### ISSUE THREAD

**Issue by benno90** [HIPS/autograd#375]
When I run the following code

    import autograd.numpy as np
    from autograd import jacobian

    def f(b):
        c = np.zeros(2)
        c[0] = b[0]*b[0]
        c[1] = b[1] * b[0] + b[2]
        return c

    b = np.array([1.0, 2.0, 2.0])
    c = f(b)

    jf = jacobian(f,0)
    j = jf(b)

I get the following error

Traceback (most recent call last):
  File "jacobian.py", line 17, in <module>
    j = jf(b)
  File "/usr/lib/python3.6/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/usr/lib/python3.6/site-packages/autograd/differential_operators.py", line 51, in jacobian
    vjp, ans = _make_vjp(fun, x)
  File "/usr/lib/python3.6/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/usr/lib/python3.6/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/usr/lib/python3.6/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "jacobian.py", line 7, in f
    c[0] = b[0]*b[0]
ValueError: setting an array element with a sequence.

Am I doing something wrong?

**Comment by duvenaud** [comment]
Autograd can't differentiate through assignment into arrays.  To get around this, you'll have to do something like building ```c``` by using ```np.concatenate()```.
