### ISSUE TITLE
Please help with wrong gradient calculation

### ISSUE THREAD

**Issue by wiedemannc** [HIPS/autograd#394]
Hi,

this is probably a stupid mistake, but I'm not able to find the root cause for the faulty gradient calculation. Using this script:

```
import numpy as np

# to test with latest autograd:
#import sys
#sys.path.insert(0, "/tmp/autograd")

from autograd import grad
import autograd.numpy as anp

def vector_to_polar(xy_real, xy_imag, _ur):
    p_raw = anp.arctan2(xy_imag, xy_real)
    amp = anp.sqrt(xy_real**2 + xy_imag**2) #norm2(xy_real, xy_imag)
    return p_raw*_ur/(2.0*anp.pi), amp

def polar_to_vector(amp, dist, _ur):
    p = dist * 2.0*anp.pi/_ur
    xy_real = anp.sum(amp * anp.cos(p), axis=0)
    xy_imag = anp.sum(amp * anp.sin(p), axis=0)
    return xy_real, xy_imag

def residuals(xy_f1, xy_meas_real, xy_meas_imag, xy_std_real, xy_std_imag, ur):
    d = 2
    xy0f1_real = xy_f1[0::d]
    xy0f1_imag = xy_f1[1::d]
    xy1f1_real = anp.ravel(xy_meas_real[0,...]) - xy0f1_real
    xy1f1_imag = anp.ravel(xy_meas_imag[0,...]) - xy0f1_imag

    d0,a0 = vector_to_polar(xy0f1_real, xy0f1_imag, ur[0])
    d1,a1 = vector_to_polar(xy1f1_real, xy1f1_imag, ur[0])

    if 0:
        # this works
        xyfi_real, xyfi_imag = polar_to_vector(anp.array([a0]), anp.array([d0]), ur[1])
    else:
        # this doesn't work
        xyfi_real, xyfi_imag = polar_to_vector(anp.array([a0,a1]), anp.array([d0,d1]), ur[1])
    return xyfi_real**2 + xyfi_imag**2

def test(XY, XYstd, ur):
    x0 = np.zeros(XY[0,...].size*2)
    x0[::2] = XY[0,...].flatten().real*0.6
    x0[1::2] = XY[0,...].flatten().imag*0.6

    residuals_cl = lambda x, *args: residuals(x, XY.real, XY.imag, XYstd.real, XYstd.imag, ur)

    res = residuals_cl(x0, "normal")
    print("\nbefore optimizing: res=", res)

    grad_residuals = grad(residuals_cl)
    g = grad_residuals(x0)
    g2 = np.zeros(g.shape)
    print("checking grad")
    for i in range(x0.size):
        eps = 1e0
        x0p = x0.copy()
        x0p[i] += eps
        yp = residuals_cl(x0p, "normal")
        x0m = x0.copy()
        x0m[i] -= eps
        ym = residuals_cl(x0m, "normal")
        g2[i] = (yp - ym)/(2*eps)
    assert np.allclose(g2, g), "num=%s vs ag=%s" % (g2, g)
    print("Grad check OK: num=%s vs ag=%s" % (g2, g))

if __name__ == "__main__":
    ur = [1, 2, 3]
    XY = np.array([[[1j-0.1]], [[-1+0.1*1j]], [[-1j+0.1]]])
    XYstd = np.array([[[0.1+0.1*1j]], [[0.1+0.1*1j]], [[0.1+0.1*1j]]])

    test(XY, XYstd, ur)
```

I am getting the following output using the latest master branch, the gradient is errorneously very small:

> before optimizing: res= [ 1.01]
> checking grad
> Traceback (most recent call last):
>   File "...autograd_test.py", line 78, in <module>
>     test(XY, XYstd, ur)
>   File "...autograd_test.py", line 70, in test
>     assert np.allclose(g2, g), "num=%s vs ag=%s" % (g2, g)
> AssertionError: num=[-0.03647315  0.40012972] vs ag=[ -8.32667268e-17   4.44089210e-16]

Changing the `if 0:` to `if 1:` results in correct gradients:

> before optimizing: res= [ 0.3636]
> checking grad
> Grad check OK: num=[-0.12  1.2 ] vs ag=[-0.12  1.2 ]

I'd be glad if anyone could give me hints about problems in the code or about advanced debugging methods in autograd.

Thank you in advance!
Christoph

**Comment by bewantbe** [comment]
I saw a line `eps = 1e0`, probably the `eps` should be something smaller?
