### ISSUE TITLE
Can't import autograd in PyPy

### ISSUE THREAD

**Issue by denyazh** [HIPS/autograd#398]
So I thought that it would be interesting to compare the execution time of Autograd in PyPy and CPython to see if PyPy's JIT compilation provides a noticeable speedup. See below:

<pre>Python 2.7.13 (ab0b9caf307d, Apr 24 2018, 18:04:42)
[PyPy 6.0.0 with GCC 6.2.0 20160901] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import numpy
>>>> numpy.version.version
'1.14.3'
>>>> import autograd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dennis/Downloads/pypy2-v6.0.0-linux64/site-packages/autograd/__init__.py", line 2, in <module>
    from .differential_operators import (
  File "/home/dennis/Downloads/pypy2-v6.0.0-linux64/site-packages/autograd/differential_operators.py", line 12, in <module>
    import autograd.numpy as np
  File "/home/dennis/Downloads/pypy2-v6.0.0-linux64/site-packages/autograd/numpy/__init__.py", line 5, in <module>
    from . import numpy_vjps
  File "/home/dennis/Downloads/pypy2-v6.0.0-linux64/site-packages/autograd/numpy/numpy_vjps.py", line 130, in <module>
    defvjp(anp.where, None,
AttributeError: 'module' object has no attribute 'where'
</pre>

**Comment by joshburkart** [comment]
Not sure this warrants an issue, though, since I doubt PyPy compatibility is on the roadmap?

**Comment by mattip** [comment]
The problem is the assumption in [this line](https://github.com/HIPS/autograd/blob/1.1.8/autograd/numpy/numpy_wrapper.py#L34) that there are only 2 python callables: `types.FunctionType` and  `types.BuiltinFunctionType`. PyPy's C-API functions are neither.
I would recommend autograd look at the `__array_ufunc__` and `__array_function__` (will be generally available in an upcoming 1.17 numpy release) protocols for overriding numpy calls. Until that is an option, could you change line 38 to  `elif callable(obj)` instead?
