### ISSUE TITLE
Hessian of neural network loss

### ISSUE THREAD

**Issue by rythei** [HIPS/autograd#413]
Thanks for a great tool! I'm interested in inspecting the hessian of a network's loss function, however I can't seem to get it to work using the ```hessian``` function:

```python
import autograd.numpy as np
from autograd import grad, hessian
from fakedata import GaussianData

def init_random_params(scale, layer_sizes, rs=np.random.RandomState(0)):
    return [(scale * rs.randn(m, n),   # weight matrix
             scale * rs.randn(n))      # bias vector
            for m, n in zip(layer_sizes[:-1], layer_sizes[1:])]

def net(X, theta):
    for W, b in theta:
        outputs = np.dot(X, W) + b
        X = np.tanh(outputs)
    return outputs

def loss(theta, X, y):
    y_hat = net(X, theta)
    return np.square(y_hat-y).mean()

if __name__ == '__main__':
    dim = 100
    layer_size = [100, 50, 1]
    param_scale = 0.1
    lr = 0.01
    n_updates = 100
    batch_size = 32

    theta = init_random_params(param_scale, layer_size)

    data = GaussianData()

    for u in range(n_updates):
        Xb, yb = data.batch(batch_size)
        grad_l = grad(loss)
        hess_l = hessian(loss)
        curr_grad = grad_l(theta, Xb, yb)
        print("Loss: ", loss(theta, Xb, yb))
        print(hess_l(theta, Xb, yb)) ####******* ERROR *********#####

        theta_temp = []
        for i in range(len(theta)):
            W_temp = theta[i][0] - lr * curr_grad[i][0]
            b_temp = theta[i][1] - lr * curr_grad[i][1]
            theta_temp.append((W_temp, b_temp))
        theta = theta_temp

```

I get the following error when trying to evaluate hess_l:

```bash
Traceback (most recent call last):
  File "/Users/rythei/Google Drive/Research/LossStability/Python/hessian-experiments/hessian_autograd_example.py", line 65, in <module>
    print(hess_l(theta, Xb, yb))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/differential_operators.py", line 72, in hessian
    return jacobian(jacobian(fun))(x)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/differential_operators.py", line 51, in jacobian
    vjp, ans = _make_vjp(fun, x)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/autograd/differential_operators.py", line 53, in jacobian
    jacobian_shape = ans_vspace.shape + vspace(x).shape
TypeError: can only concatenate tuple (not "list") to tuple
```
I've tried casting theta as a numpy array, but to no avail. Any suggestions? Thank you!

**Comment by bewantbe** [comment]
In my experience, you have to make the `theta` a single numpy array (or something equivalent) for hessian() or jacobian() to work correctly. e.g. linearize and concatenate them into a vector.

See also [examples/convnet.py](https://github.com/HIPS/autograd/blob/master/examples/convnet.py). Note the `class WeightsParser` is for helping flatten and concatenate the variables.
