### ISSUE TITLE
Error in grad when using arctan2 function

### ISSUE THREAD

**Issue by joddlehod** [HIPS/autograd#414]
The autograd function arctan2 seems to work fine on its own:

```
>>> import autograd.numpy as anp
>>> anp.arctan2(1.0, 0.0)
1.5707963267948966
>>>
```

But when I try to `grad` a function that uses arctan2, I get an error:

Contents of `test_arctan2.py`:
```
import autograd.numpy as anp
from autograd import grad

def arctan2(xy):
    return anp.arctan2(xy[1], xy[0])

garctan2 = grad(arctan2)
garctan2((0.0, 1.0))
```

Output of `test_arctan2.py`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hodsonjd/dev/test_arctan2.py", line 9, in <module>
    print(garctan2((0.0, 1.0)))
  File "/home/hodsonjd/.linuxbrew/Cellar/python/3.6.5/lib/python3.6/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/home/hodsonjd/.linuxbrew/Cellar/python/3.6.5/lib/python3.6/site-packages/autograd/differential_operators.py", line 24, in grad
    vjp, ans = _make_vjp(fun, x)
  File "/home/hodsonjd/.linuxbrew/Cellar/python/3.6.5/lib/python3.6/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/home/hodsonjd/.linuxbrew/Cellar/python/3.6.5/lib/python3.6/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/home/hodsonjd/.linuxbrew/Cellar/python/3.6.5/lib/python3.6/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "/home/hodsonjd/dev/test_arctan2.py", line 5, in arctan2
    return anp.arctan2(xy[1], xy[0])
  File "/home/hodsonjd/.linuxbrew/Cellar/python/3.6.5/lib/python3.6/site-packages/autograd/tracer.py", line 45, in f_wrapped
    node = node_constructor(ans, f_wrapped, argvals, kwargs, argnums, parents)
  File "/home/hodsonjd/.linuxbrew/Cellar/python/3.6.5/lib/python3.6/site-packages/autograd/core.py", line 30, in __init__
    self.vjp = primitive_vjps[fun](parent_argnums, value, args, kwargs)
KeyError: <function primitive.<locals>.f_wrapped at 0x7f57be01ea60>
```

I am quite new to autograd (just started working with it yesterday), so this may simply be user error. If someone can offer some insight as to what I might be doing wrong, any help would be greatly appreciated!

Thanks,
Josh

**Comment by j-towns** [comment]
Try installing Autograd from the master branch on Github. I think support for numpy.arctan2 was only add relatively recently and isn't yet in the version on PyPI.

**Comment by joddlehod** [comment]
You are right, arctan2 seems to work with the master branch. thanks!
