### ISSUE TITLE
1 layer perceptron for MNIST gives memoryerror

### ISSUE THREAD

**Issue by ayush1999** [HIPS/autograd#421]
Hey, I just love this package. Thanks a ton for this.
I was implementing a simple 1 layer preceptron for MNIST recognition using autograd. The data has a shape `60000x784` and output has shape `60000,1`

I'm using the mse loss function, and trying to optimize it using autograd. Here is the relevant snippet of my code:

```
w1 = np.zeros([784, 1])

def loss(w):
    return sum((np.dot(x_train, w) - y_train)**2)

for i in range(50):
    w1 -= grad(loss)(w1)*0.001
    print(loss(w1))
```

As I run the script, it crashes with a memoryerror: 

```
Traceback (most recent call last):
  File "sin.py", line 16, in <module>
    w1 -= grad(loss)(w1)*0.001
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/autograd/differential_operators.py", line 24, in grad
    vjp, ans = _make_vjp(fun, x)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "sin.py", line 13, in loss
    return sum((np.dot(x_train, w) - y_train)**2)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/autograd/numpy/numpy_boxes.py", line 25, in __sub__
    def __sub__(self, other): return anp.subtract(self, other)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/autograd/tracer.py", line 44, in f_wrapped
    ans = f_wrapped(*argvals, **kwargs)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
MemoryError
```

I wanter to know what can be the reason behind this? I there something wrong in the way I'm trying to optimize the loss function?

**Comment by j-towns** [comment]
A MemoryError suggests you're running out of memory for some reason. One thing which might help is replacing the native Python `sum` with the Numpy `np.sum`. This will certainly reduce Autograd's memory (and time) overhead, because it will save having to store a separate object for each summand.

**Comment by ayush1999** [comment]
@j-towns Just tried it out, still the same error. Is it possible there is an error in my implementation of my loss grad?

**Comment by j-towns** [comment]
Could you post the full code so I can try to reproduce the issue?

**Comment by ayush1999** [comment]
Sure:
```import autograd.numpy as np
from autograd import grad

ip = np.random.randn(60000, 784)
op = np.random.randn(60000)

w1 = np.zeros([784, 1])

def loss(w):
    return np.sum((np.dot(ip, w) - op)**2)

for i in range(50):
    w1 -= grad(loss)(w1)*0.005
    print(loss(w1))
```

I've taken some dummy data for now, just to test out the code.

**Comment by rsokl** [comment]
Can confirm. The following

```python
import autograd.numpy as np
from autograd import grad

ip = np.random.randn(60000, 784)
op = np.random.randn(60000)

w1 = np.zeros([784, 1])

def loss(w):
    return np.sum((np.dot(ip, w) - op)**2)

l = grad(loss)
w1 -= l(w1)
```

Just consumed 16GB of RAM

**Comment by j-towns** [comment]
Ah I think I can see the issue. The expression `np.dot(ip, w)` results in an array with shape (60000, 1). The array `op` has shape (60000), so broadcasting means that `np.dot(ip, w) - op` has shape (60000, 60000), which is big.

I think the easiest way to fix this is to make `w1` a 1D array with shape (784,). So
```python
import autograd.numpy as np
from autograd import grad

ip = np.random.randn(60000, 784)
op = np.random.randn(60000)

w1 = np.zeros(784)

def loss(w):
    return np.sum((np.dot(ip, w) - op)**2)

l = grad(loss)
w1 -= l(w1)
```

PS: Glad you like Autograd!

**Comment by j-towns** [comment]
Is it ok to close this?
