### ISSUE TITLE
scipy.stats "setting array element with a sequence" error

### ISSUE THREAD

**Issue by matthewdhoffman** [HIPS/autograd#422]
When I try to run the following snippet:
```python
from autograd import grad
from autograd import numpy as np
from autograd import scipy

n_dimensions = 2
n_examples = 1000

def linear_regression_log_likelihood(beta, x, y):
    predictions = x.dot(beta)
    return scipy.stats.norm.logpdf(y, loc=predictions, scale=1.).sum(-1)

fake_args = [np.zeros(n_dimensions), np.zeros([n_examples, n_dimensions]),
np.zeros(n_examples)]
grad(linear_regression_log_joint)(*fake_args)
```

I get this error:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 14, in <module>
    grad(linear_regression_log_joint)(*fake_args)
  File "/usr/local/lib/python2.7/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/usr/local/lib/python2.7/site-packages/autograd/differential_operators.py", line 24, in grad
    vjp, ans = _make_vjp(fun, x)
  File "/usr/local/lib/python2.7/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/usr/local/lib/python2.7/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/usr/local/lib/python2.7/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "/tmp/test.py", line 11, in linear_regression_log_joint
    return scipy.stats.norm.logpdf(y, loc=predictions, scale=1.).sum(-1)
  File "/usr/local/lib/python2.7/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1691, in logpdf
    x = np.asarray((x - loc)/scale, dtype=dtyp)
  File "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

**Comment by duvenaud** [comment]
This can be fixed by replacing
```scipy.stats.norm.logpdf(y, loc=predictions, scale=1.)```
with
```scipy.stats.norm.logpdf(y, predictions, scale=1.)```

Right now autograd doesn't differentiate through named arguments, unfortunately.
