### ISSUE TITLE
Exception when computing the gradient of a function that uses np.pad

### ISSUE THREAD

**Issue by crowsonkb** [HIPS/autograd#441]
Using both the version of autograd on PyPI and the master branch, I get an exception when trying to compute the gradient of a function that uses `np.pad`. Here is a simple example:

```python
from autograd import grad
import autograd.numpy as np


def f(x):
    x = np.pad(x, ((1, 1),), 'constant')
    return np.sum(x**2)

g = grad(f)
g(np.zeros(2))
```

This raises the exception:

```python-traceback
Traceback (most recent call last):
  File "pad_demo.py", line 10, in <module>
    g(np.zeros(2))
  File "/Users/kat/Documents/projects/pylab/venv/lib/python3.7/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/Users/kat/Documents/projects/pylab/venv/lib/python3.7/site-packages/autograd/differential_operators.py", line 24, in grad
    vjp, ans = _make_vjp(fun, x)
  File "/Users/kat/Documents/projects/pylab/venv/lib/python3.7/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/Users/kat/Documents/projects/pylab/venv/lib/python3.7/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/Users/kat/Documents/projects/pylab/venv/lib/python3.7/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "pad_demo.py", line 6, in f
    x = np.pad(x, ((1, 1),), 'constant')
  File "/Users/kat/Documents/projects/pylab/venv/lib/python3.7/site-packages/autograd/tracer.py", line 45, in f_wrapped
    node = node_constructor(ans, f_wrapped, argvals, kwargs, argnums, parents)
  File "/Users/kat/Documents/projects/pylab/venv/lib/python3.7/site-packages/autograd/core.py", line 30, in __init__
    self.vjp = primitive_vjps[fun](parent_argnums, value, args, kwargs)
KeyError: <function primitive.<locals>.f_wrapped at 0x109928950>
```

**Comment by j-towns** [comment]
This should work fine since https://github.com/HIPS/autograd/commit/7b61be3d1cb0a773c6e6bfe4b7a27c79b500935b. Can you make sure to pull down the most recent `master`?

**Comment by crowsonkb** [comment]
I just re-ran `pip install git+https://github.com/HIPS/autograd` to make sure I had the `master` branch, and I still get this error.

**Comment by crowsonkb** [comment]
Sorry, I should have pulled down `master` using `pip install -U git+https://github.com/HIPS/autograd`. It works for me now.
