### ISSUE TITLE
Having issues with autograd and NonlinearConstraint

### ISSUE THREAD

**Issue by hroskes** [HIPS/autograd#484]
I'm trying to calculate the minimum of a function using a `NonlinearConstraint`, and I'm using autograd to get all my derivatives.  For the input to minimize itself, everything works fine.  For `NonlinearConstraint`, `hessian_vector_product` seems to not be working.  I'm not sure if this is an autograd issue or a scipy issue.

Here's a simple example.

```
useconstraint = False

import autograd
import autograd.numpy as np
from scipy import optimize

def function(x): return x[0]**2 + x[1]**2
functionjacobian = autograd.jacobian(function)
functionhvp = autograd.hessian_vector_product(function)

def constraint(x): return np.array([x[0]**2 - x[1]**2])
constraintjacobian = autograd.jacobian(constraint)
constrainthvp = autograd.hessian_vector_product(constraint)

constraint = optimize.NonlinearConstraint(constraint, 1, np.inf, constraintjacobian, constrainthvp)

startpoint = [1, 2]

bounds = optimize.Bounds([-np.inf, -np.inf], [np.inf, np.inf])

print optimize.minimize(
  function,
  startpoint,
  method='trust-constr',
  jac=functionjacobian,
  hessp=functionhvp,
  constraints=[constraint] if useconstraint else [],
  bounds=bounds,
)
```

With `useconstraint = False` everything is fine.  When I set it to true, I get an error:

```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    bounds=bounds,
  File "/home/heshy/.local/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 613, in minimize
    callback=callback, **options)
  File "/home/heshy/.local/lib/python2.7/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 336, in _minimize_trustregion_constr
    for c in constraints]
  File "/home/heshy/.local/lib/python2.7/site-packages/scipy/optimize/_constraints.py", line 213, in __init__
    finite_diff_bounds, sparse_jacobian)
  File "/home/heshy/.local/lib/python2.7/site-packages/scipy/optimize/_differentiable_functions.py", line 343, in __init__
    self.H = hess(self.x, self.v)
  File "/home/heshy/.local/lib/python2.7/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/home/heshy/.local/lib/python2.7/site-packages/autograd/differential_operators.py", line 24, in grad
    vjp, ans = _make_vjp(fun, x)
  File "/home/heshy/.local/lib/python2.7/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/home/heshy/.local/lib/python2.7/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/home/heshy/.local/lib/python2.7/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "/home/heshy/.local/lib/python2.7/site-packages/autograd/differential_operators.py", line 88, in vector_dot_grad
    return np.tensordot(fun_grad(*args, **kwargs), vector, np.ndim(vector))
  File "/home/heshy/.local/lib/python2.7/site-packages/autograd/tracer.py", line 44, in f_wrapped
    ans = f_wrapped(*argvals, **kwargs)
  File "/home/heshy/.local/lib/python2.7/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/home/heshy/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 1371, in tensordot
    raise ValueError("shape-mismatch for sum")
ValueError: shape-mismatch for sum
```

I'm not sure if this is an autograd issue or a scipy issue.  If scipy expects something different for the hessian for `NonlinearConstraint`, could autograd provide this function?

**Comment by hroskes** [comment]
Ok, I found the issue.  A "Hessian-vector product" is not the same thing as a "linear combination of Hessians."

I think this function would work:

```
def linear_combination_of_hessians(fun, argnum=0, *args, **kwargs):
  """
  Returns a function that computes the linear combination of hessians.
  """
  functionhessian = hessian(fun, argnum, *args, **kwargs)
  #not using wrap_nary_f because we need to do the docstring on our own
  def linear_combination_of_hessians(*funargs, **funkwargs):
    print np.tensordot(functionhessian(*args[:-1]), args[-1], axes=(0, 0))

  linear_combination_of_hessians.__name__ = functionhessian.__name__.replace(
    "hessian", "linear_combination_of_hessians", 1
  )

  linear_combination_of_hessians.__doc__ = """
    linear combination of hessians of function {fun.__name__} with respect to
    argument number {argnum}.  Takes the same arguments as {fun.__name__} plus a vector
    (given as a final, non-keyword argument) to dot with the hessians.
  """.lstrip("\n").format(fun=fun, argnum=argnum)
```

But I haven't tried it yet.

**Comment by peterdsharpe** [comment]
Hey @hroskes , did this solution work? I'm running into the same issue as you!

**Comment by hroskes** [comment]
Hi @peterdsharpe, I'm fairly certain that it did.  My head isn't in this anymore, because I had to move to a non-analytic constraint, so autograd wasn't an option.  According to the readme (new since the last time I used) autograd is now migrated to JAX, so you might have better success asking over there.

**Comment by peterdsharpe** [comment]
@hroskes ,

Awesome - thanks for the quick response! 

JAX is a great suggestion, but unfortunately we need to retain Windows-compatibility (which remains to be implemented in JAX due to XLA compilation issues). Perhaps PyTorch might be an easier option, considering it has its own large-scale NLP solvers...

Thanks again for your help!
