### ISSUE TITLE
Arraybox with logsumexp

### ISSUE THREAD

**Issue by leoouyang** [HIPS/autograd#485]
When trying to use the logsumexp() from autograd.scipy.misc, I got the following error: 
Traceback (most recent call last):
  File "C:/Leo/csc412/A2/q3.py", line 91, in <module>
    w = grad_descent(cost, train_images, train_labels, w, 0.00001, 10000)
  File "C:/Leo/csc412/A2/q3.py", line 73, in grad_descent
    w -= alpha*df(w, cur_x, y)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\differential_operators.py", line 24, in grad
    vjp, ans = _make_vjp(fun, x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "C:/Leo/csc412/A2/q3.py", line 55, in cost
    sum = sum + log_prob(cs[i], x[:,i], w)
  File "C:/Leo/csc412/A2/q3.py", line 27, in log_prob
    log_denominator = logsumexp(wtx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\special\_logsumexp.py", line 92, in logsumexp
    a = _asarray_validated(a, check_finite=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\_lib\_util.py", line 241, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported

**Comment by leoouyang** [comment]
from __future__ import absolute_import
from __future__ import print_function
from future.standard_library import install_aliases
install_aliases()

import autograd.numpy as np
import autograd.numpy.random as npr
from autograd import grad
from autograd.misc.optimizers import adam
from autograd.scipy.misc import logsumexp
from autograd.scipy.special import expit as sigmoid

import os
import gzip
import struct
import array

import matplotlib.pyplot as plt
import matplotlib.image
from urllib.request import urlretrieve

from data import *

def log_prob(c, x, w):
    log_numerator = np.dot(w.T[c, :], x)
    wtx = np.dot(w.T, x)
    log_denominator = logsumexp(wtx)
    return log_numerator - log_denominator

def cost(w, x, y):
    # cost is the sum of negative log porbs for
    # log(a/b) = log(a) - log(b)

    # print(np.array(w))
    # wtx = np.dot(w.T, x)
    # log_denominator = logsumexp(wtx,axis = 0)
    # w_selected = w[:,y.nonzero()[1]] #result in an 784 x 10000 weight matrix, each column
    #                                 # are the weights correspond to an sample's label
    # wx = w_selected*x
    # # log_numerator = np.sum(wx, axis = 0)
    # log_numerator = np.zeros(log_denominator.shape)
    # for i in range(log_numerator.shape[0]):
    #     sum = 0
    #     for j in range(wx.shape[0]):
    #         sum += wx[j,i]
    #     log_numerator[i] = sum
    # # print(log_numerator.shape)
    # print(log_numerator)
    # print(log_denominator)
    cs = y.nonzero()[1]
    sum = 0
    for i in range(x.shape[1]):
        sum = sum + log_prob(cs[i], x[:,i], w)
    average_log_prob = sum/x.shape[1]
    cost = -average_log_prob
    return cost

def grad_descent(cost, x, y, init_w, alpha, max_iter):
    #w is 784 x 10
    EPS = 1e-6
    prev_w = init_w-10*EPS
    w = init_w.copy()
    iter = 0
    df = grad(cost, 0)
    print('Doing gradient Descent')
    cur_x = x.T #transpose x such that each column correspond to 1 sample, x is 784*10000
    while np.linalg.norm(w - prev_w) > EPS and iter < max_iter:
        print(iter)
        print("Cost: " + str(cost(w, cur_x, y)))
        prev_w = w.copy()
        w -= alpha*df(w, cur_x, y)
        if iter % 100 == 0:
            print("Iter"+ str(iter))
            print("Cost: "+ str(cost(w, cur_x, y)))
        #     print "theta = ", t, ", f(x) = %.2f" % (f(x, y, t))
        #     print "Gradient: ", df(x, y, t), "\n"
        iter += 1
    print('Final Cost is ' + format(cost(w, cur_x, y), '.2f'))
    return w

if __name__ == "__main__":
    N_data, train_images, train_labels, test_images, test_labels = load_mnist()
    train_images = np.round(train_images[0:10000])
    train_labels = train_labels[0:10000]
    test_images = np.round(test_images[0:10000])
    test_labels = test_labels[0:10000]

    w = np.random.rand(784,10)
    w = grad_descent(cost, train_images, train_labels, w, 0.00001, 10000)
