### ISSUE TITLE
`ValueError: setting an array element with a sequence.` while using grad

### ISSUE THREAD

**Issue by mahaksinghchauhan** [HIPS/autograd#515]
Hello all,
I am using grad for calculating the derivative of my fitness function. However I am getting a value error as following:

`ValueError: setting an array element with a sequence.`

I printed the type and value of the final output and find that the value contains the text also. Can anyone suggest me what should I do ?

Print of Type and Value:

```
Type of Output  <class 'autograd.numpy.numpy_boxes.ArrayBox'>
Value of Output=  Autograd ArrayBox with value Autograd ArrayBox with value Autograd ArrayBox with value Autograd ArrayBox with value -32.248885305979115
```
I suppose, because of that text the function creating problem while return the value. Looking forward for your help.
Thank You

**Comment by flaudanum** [comment]
Hello,
I'm facing a similar issue with the same puzzling error message. Here a code raising this exception. It seems that jacobian cannot deal with the matrix-block assignment.
```python
import autograd.numpy as np
from autograd import jacobian

size = 2
mat = np.diag([4,6,6,3])
def func(x):
    diag_xx = np.zeros(shape=(size, 2*size))
    diag_xx[:size,:size] = np.diag(x)
    diag_xx[:size,size:] = np.diag(x)
    xx = np.hstack((x,x))
    return np.dot(diag_xx @ mat, xx)

jac = jacobian(func)
x = np.array([1.,2.])
print(func(x))
print(jac(x))
```
Computing the function is OK and prints:
```
array([10., 36.])
```
But jac(x) raises:
```
ValueError: setting an array element with a sequence.
```
while indicating the code line:
```python
diag_xx[:size,:size] = np.diag(x)
```
This is a useful project and this is bad luck that I'm facing this issue. Should I move to your new project [JAX](https://github.com/google/jax)?
Thanks for the help.

**Comment by mahaksinghchauhan** [comment]
Hi, I have been looking to do something for your problem but couldn't find a proper solution.

But it's sure that autograd do not support vectorization of the code. so far in your case I think the assignment in the following line creating the problem.

 `diag_xx[:size,:size] = np.diag(x)`

if somehow you can change the code, I think it will work. I did the same. Sorry for not coming out with a precise answer. Similar issues:

https://github.com/HIPS/autograd/issues/177

https://github.com/HIPS/autograd/issues/422

https://github.com/HIPS/autograd/issues/364

https://github.com/HIPS/autograd/issues/365

Examples:
https://www.programcreek.com/python/example/97137/autograd.numpy.sum

Supported numpy functions:
https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_vjps.py

**Comment by josh-bone** [comment]
I am getting this error, but I don't believe I'm doing any vector assignment. I'm just initializing numpy arrays:

# unpack parameters
ksi_1, ksi_2, ku_1, kv_1, skew_1, uo_1, vo_1, ku_2, kv_2, skew_2, uo_2, vo_2, z, theta = params

```
K1 = np.array([[ku_1, skew_1, uo_1],
                [0, kv_1, vo_1],
                [0, 0, 1]], dtype=float)
K2 = np.array([[ku_2, skew_2, uo_2],
                [0, kv_2, vo_2],
                [0, 0, 1]], dtype=float)
rotMat = np.array([[np.cos(theta), -np.sin(theta)],
                    [np.sin(theta), np.cos(theta)]], dtype=float)
```


Traceback:
```
TypeError: float() argument must be a string or a number, not 'ArrayBox'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "SGD_parameters_np.py", line 103, in <module>
    gradient = grad_fn(params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\differential_operators.py", line 25, in grad
    vjp, ans = _make_vjp(fun, x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autograd\wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "SGD_parameters_np.py", line 66, in training_loss
    pred = prediction(x_train, params)
  File "SGD_parameters_np.py", line 22, in prediction
    [0, 0, 1]], dtype=float)
ValueError: setting an array element with a sequence.
```

**Comment by CamDavidsonPilon** [comment]
@josh-bone, it looks like the cause may be 
```
TypeError: float() argument must be a string or a number, not 'ArrayBox'
```

The params, `ksi_1`, etc. are not _floats_, but autograd objects. But you're asking numpy to convert them to floats in your `np.array` call

**Comment by josh-bone** [comment]
I am passing the params as floats, though. 

Would this happen when I call the function through grad(function)?

**Comment by CamDavidsonPilon** [comment]
mm I'm not sure I understand your question - can you post your entire code?

**Comment by josh-bone** [comment]
```
def prediction(alpha_prime, params):
    assert np.shape(alpha_prime) == (1, 2) or np.shape(
        alpha_prime) == (2,), "Unexpected shape for alpha_prime"

    # unpack parameters
    ksi_1, ksi_2, ku_1, kv_1, skew_1, uo_1, vo_1, ku_2, kv_2, skew_2, uo_2, vo_2, z, theta = params
    for p in params:
        if type(p) == <class 'autograd.numpy.numpy_boxes.ArrayBox' >:
            print("arrayBOx!")

    K1 = np.array(
        [[ku_1, skew_1, uo_1], [0.0, kv_1, vo_1], [0.0, 0.0, 1.0]])
    K2 = np.array(
        [[ku_2, skew_2, uo_2], [0.0, kv_2, vo_2], [0.0, 0.0, 1.0]])
    # this angular displacement will be applied to beta_prime coordinates, after K2
    cosin_val = np.cos(theta)
    sin_val = np.sin(theta)
    rotMat = np.array([[cosin_val, -sin_val],
                       [sin_val, cosin_val]])

    alpha_prime = np.append(alpha_prime, 1.0)
    alpha = np.dot(np.linalg.inv(K1), alpha_prime)
    # coefficients, where quadratic formula is quad_a * u**2 + quad_b * u + quad_c = 0
    quad_a = 1.0/alpha[0]**2 - (ksi_1 ** 2.0) * \
        (1.0 + (alpha[1]**2.0)/(alpha[0]**2.0))
    quad_b = -2.0/alpha[0]
    quad_c = 1.0 - ksi_1**2

    if(quad_b**2 < 4*quad_a*quad_c):
        print("u is complex")
    u_plus = (-quad_b + np.sqrt(quad_b**2.0 - 4.0*quad_a*quad_c))/(2.0*quad_a)
    u_minus = (-quad_b - np.sqrt(quad_b**2.0 - 4.0*quad_a*quad_c))/(2.0*quad_a)

    # trying this out
    if(alpha[0] >= 0):
        u = u_plus
    else:
        u = u_minus

    if(alpha[0] == 0):
        # avoid divide-by-zero error. Causes a weird dot in the final plot, we should talk about this
        v = alpha[1]/.000000001 * u
    else:
        v = alpha[1]/alpha[0] * u
    x_est = z * u
    y_est = z * v

    b1_est = (x_est - d)/(z + ksi_2 *
                          np.sqrt((x_est - d)**2 + y_est**2 + z**2))
    b2_est = y_est / (z + ksi_2*np.sqrt((x_est - d)**2 + y_est**2 + z**2))
    b = np.array([b1_est, b2_est, 1.0])
    B_prime = np.dot(rotMat, np.dot(K2, b)[:2])

    return(B_prime)


def training_loss(params):
    pred = prediction(x_train, params)
    return((y_train[1] - pred[0])**2 + (y_train[1] - pred[1])**2)


if __name__ == '__main__':
    # initialize "expected" parameters
    d = 3
    z = 2
    ku_1, kv_1, ku_2, kv_2 = 1, 1, 1, 1
    theta = 0  # angular displacement
    # (uo, vo) is the center of image in pixels
    skew_1, uo_1, vo_1 = 0, 1024/2, 1024/2
    skew_2, uo_2, vo_2 = 0, 1024/2, 1024/2
    ksi_1, ksi_2 = 1, 1  # distortion parameters
    params = [ksi_1, ksi_2, ku_1, kv_1, skew_1,
              uo_1, vo_1, ku_2, kv_2, skew_2, uo_2, vo_2, z, theta]
    params = np.array(params, dtype=float)

    left_file = "leftlabels"
    right_file = "rightlabels"
    with open(left_file, 'rb') as f:
        Xpix = pickle.load(f)
    Xpix = np.array(Xpix, dtype=float)
    with open(right_file, 'rb') as f:
        Ypix = pickle.load(f)
    Ypix = np.array(Ypix, dtype=float)

    grad_fn = grad(training_loss)
    num_epochs = 50
    lr = 0.01
    losses = []
    for e in range(num_epochs):
        for i, x in enumerate(Xpix):
            x_train = x
            y_train = Ypix[i, :]
            loss = training_loss(params)
            losses.append(loss)
            gradient = grad_fn(params)
            params = params - lr * gradient
```

**Comment by CamDavidsonPilon** [comment]
Is it possible for you to paste a minimally reproducible example? I'm not able to run your code

**Comment by josh-bone** [comment]
Sorry, I've edited it to be reproducible. I forgot I was loading the data from file at first.

**Comment by duvenaud** [comment]
I suspect you can fix these problems by changing ```import numpy as np``` to ```import autograd.numpy as np```
