### ISSUE TITLE
Function for *Full* Forward Mode Jacobian

### ISSUE THREAD

**Issue by twhughes** [HIPS/autograd#524]
Following Issue #439, I'm interested in implementing a version of the `jacobian` function from `differential_operators.py` but using forward mode differentiation.

From this [comment](https://github.com/HIPS/autograd/issues/439#issuecomment-430562833) from @j-towns, it seems to make this work one would need `To get the full Jacobian of f you just need to write a loop to evaluate make_jvp(f)(x)(v) for each v in the standard basis of f's domain.`

I'm trying to implement this below but running into some issues and would really appreciate help.

The reverse mode `jacobian` function defined in `differential_operators.py` is copied below:

```python
@unary_to_nary
def jacobian_backward(fun, x):
    vjp, ans = _make_vjp(fun, x)
    ans_vspace = vspace(ans)
    jacobian_shape = ans_vspace.shape + vspace(x).shape
    grads = map(vjp, ans_vspace.standard_basis())
    return np.reshape(np.stack(grads), jacobian_shape)
```

I am trying to implement a forward mode version of this function using `make_jvp` instead of `make_vjp `, which is pasted below

```python
@unary_to_nary
def jacobian_forward(fun, x):
    jvp, ans = _make_jvp(fun, x)
    ans_vspace = vspace(ans)
    jacobian_shape = ans_vspace.shape + vspace(x).shape
    grads = map(jvp, ans_vspace.standard_basis())
    return np.reshape(np.stack(grads), jacobian_shape)
```

However, this gives errors when run.  Here is a very simple code sample to reproduce, using these two functions:

```python
N = 2
A = np.random.random((N,N))
print('A = \n', A)

def fn(x):
   # partial of this fn w.r.t. `x` should be `A`
    return A @ x

x0 = np.random.random((N,))
print('Jac_rev = \n', jacobian_backward(fn)(x0))
print('Jac_for = \n', jacobian_forward(fn)(x0))
```

Which gives the following output

```
A =
 [[0.24700088 0.60585769]
 [0.02701674 0.71704424]]
Jac_rev =
 [[0.24700088 0.60585769]
 [0.02701674 0.71704424]]
Traceback (most recent call last):
  File "forward_test.py", line 67, in <module>
    print('Jac_for = \n', jacobian_forward(fn)(x0))
  File ".../anaconda3/lib/python3.7/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "forward_test.py", line 34, in jacobian_forward
    jvp, ans = _make_jvp(fun, x)
TypeError: cannot unpack non-iterable function object
```

As you can see, the reverse mode works fine but the forward mode gives an error when trying to make the jvp.

Do you have any ideas on how to construct a forward version of the standard `jacobian` function?

Thanks for your help

**Comment by twhughes** [comment]
update:
I managed to get it working, the code is below 
```python
@unary_to_nary
def jacobian_forward(fun, x):
    """
    Returns a function which computes the Jacobian of `fun` with respect to
    positional argument number `argnum`, which must be a scalar or array. Unlike
    `grad` it is not restricted to scalar-output functions, but also it cannot
    take derivatives with respect to some argument types (like lists or dicts).
    If the input to `fun` has shape (in1, in2, ...) and the output has shape
    (out1, out2, ...) then the Jacobian has shape (out1, out2, ..., in1, in2, ...).
    """
    jvp = _make_jvp(fun, x)
    ans = fun(x)
    ans_vspace = vspace(ans)
    jacobian_shape = ans_vspace.shape + vspace(x).shape
    jac_return = np.zeros(jacobian_shape)
    for i, basis_vec in enumerate(ans_vspace.standard_basis()):
        _, grad = jvp(basis_vec)
        jac_return[:,i] = grad
    return jac_return
```
