### ISSUE TITLE
*=, /= operators don't coerce double to complex

### ISSUE THREAD

**Issue by a1k0n** [HIPS/autograd#77]
I am not so sure about the underlying cause; the description is my best guess. Came across this designing IIR filters... Not-totally-minimal test case:

```
import autograd.numpy as np
import autograd


def f1(x):
    z = np.exp(1j*np.linspace(0, 3, 10))
    p1 = np.exp(1j * x - 0.1)
    h = z + 1.0
    h /= (z - p1) * (z - np.conj(p1))
    return np.mean(np.abs(h))


def f2(x):
    z = np.exp(1j*np.linspace(0, 3, 10))
    p1 = np.exp(1j * x - 0.1)
    h = (z + 1.0) / ((z - p1) * (z - np.conj(p1)))
    return np.mean(np.abs(h))


print autograd.value_and_grad(f2)(0.1)
# Works OK, produces (13.965532859262613, -107.22571311244289)
print autograd.value_and_grad(f1)(0.1)
# Crashes with:

Traceback (most recent call last):
  File "cplx.py", line 21, in <module>
    print autograd.value_and_grad(f1)(0.1)
  File "/Users/andy/.py/lib/python2.7/site-packages/autograd/convenience_wrappers.py", line 47, in value_and_grad_fun
    gradval, val = gradval_and_val(*args, **kwargs)
  File "/Users/andy/.py/lib/python2.7/site-packages/autograd/convenience_wrappers.py", line 33, in grad_and_aux_fun
    gradval = grad(return_val_save_aux, argnum)(*args, **kwargs)
  File "/Users/andy/.py/lib/python2.7/site-packages/autograd/core.py", line 21, in gradfun
    return backward_pass(*forward_pass(fun,args,kwargs,argnum))
  File "/Users/andy/.py/lib/python2.7/site-packages/autograd/core.py", line 63, in forward_pass
    except Exception as e: add_extra_error_message(e)
  File "/Users/andy/.py/lib/python2.7/site-packages/autograd/core.py", line 392, in add_extra_error_message
    raise_(etype, value, traceback)
  File "/Users/andy/.py/lib/python2.7/site-packages/autograd/core.py", line 62, in forward_pass
    try: end_node = fun(*args, **kwargs)
  File "/Users/andy/.py/lib/python2.7/site-packages/autograd/convenience_wrappers.py", line 30, in return_val_save_aux
    val, aux = fun(*args, **kwargs)
  File "/Users/andy/.py/lib/python2.7/site-packages/autograd/convenience_wrappers.py", line 42, in double_val_fun
    val = fun(*args, **kwargs)
  File "cplx.py", line 9, in f1
    h /= (z - p1) * (z - np.conj(p1))
TypeError: ufunc 'divide' output (typecode 'O') could not be coerced to provided output parameter (typecode 'D') according to the casting rule ''same_kind''
```

Same thing happens with *= vs *.

**Comment by mattjj** [comment]
Autograd doesn't support in-place operations on arrays. Would that explain things?

**Comment by a1k0n** [comment]
Ah I see. Yes, that could explain it; h is an array, and if I do the operations one-at-a-time it works fine.

I didn't realize that was a restriction. The /= operation does actually work in some array cases, just not others. For instance, this actually works fine with autograd:

```
def f2(x):
    z = np.exp(1j*np.linspace(0, 3, 10))
    p1 = np.exp(1j * x - 0.1)
    h = (z + 1.0) / (z - p1)
    h /= (z - np.conj(p1))
    return np.mean(np.abs(h))
```

I haven't looked into what typecodes O and D are, but it seems like it works as long as the types are both complex... but the thing is in the first test case which fails they are also complex. I don't know.

Anyway if I'm using an unsupported operation, then feel free to close.

**Comment by mattjj** [comment]
My guess is the typecode 'O' thing refers to an object array, which is how numpy is seeing the autograd `ComplexArrayNode` instance when dispatching to that ndarray's inplace division method. 

In my opinion, it's probably a good idea to avoid inplace operations even if they seem to work. And always call `quick_grad_check` or something like it to double check with finite differences!

I'm going to close the issue because inplace ops aren't supported.

**Comment by a1k0n** [comment]
Ok, thanks for the clarification, and thanks for being so responsive! autograd is great.
